export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';

export const GET_INITIAL_MOVIES = 'GET_INITIAL_MOVIES';

export const   GET_SEARCH_MOVIE = 'GET_SEARCH_MOVIE';

export const  GET_SEARCHED_MOVIE_DESC = 'GET_SEARCHED_MOVIE_DESC'; 

export const ADD_MOVIE_TO_BOOKMARK = 'ADD_MOVIE_TO_BOOKMARK';

export const GET_ALL_BOOKMARK_MOVIE = 'GET_ALL_BOOKMARK_MOVIE';